MODEL:
  OUTPUT_PATH: "/home/apie/projects/ml_hw/hw2/weights/model.pth"
  LR: 0.001
  EPOCH: 1

DATA:
  TRAIN_BATCH_SIZE: 32
  TEST_BATCH_SIZE: 1
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]
  RESIZE: [224, 224]
  NUM_WORKERS: 4

PATH:
  TRAIN_SET: "/home/apie/projects/ml_hw/hw1/Cat_Dog_data/train"
  TEST_SET: "/home/apie/projects/ml_hw/hw2/Cat_Dog_data/test"

DEVICE:
  GPU: 1
  CUDA: True
